from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
from botocore.config import Config
from botocore.exceptions import ClientError
import boto3
import os
import json
import uuid
import re


# ============================================================
# ENVIRONMENT
# ============================================================

CORS_ORIGINS = os.getenv(
    "CORS_ORIGINS",
    "*"
)

AWS_REGION = os.getenv(
    "DEFAULT_AWS_REGION",
    "us-east-1"
)

# Use the global inference profile so Bedrock can route to supported regions.
BEDROCK_MODEL_ID = os.getenv(
    "BEDROCK_MODEL_ID",
    "global.amazon.nova-2-lite-v1:0"
)

USE_S3 = os.getenv(
    "USE_S3",
    "true"
).lower() == "true"

S3_BUCKET = os.getenv(
    "S3_BUCKET",
    ""
)

MEMORY_DIR = os.getenv(
    "MEMORY_DIR",
    "/tmp/memory"
)


# ============================================================
# VALIDATION
# ============================================================

if not BEDROCK_MODEL_ID:
    raise RuntimeError(
        "BEDROCK_MODEL_ID is not configured."
    )

if not AWS_REGION:
    raise RuntimeError(
        "DEFAULT_AWS_REGION is not configured."
    )


# ============================================================
# FASTAPI
# ============================================================

app = FastAPI(
    title="AI Digital Twin API",
    version="1.1.0"
)


# ============================================================
# CORS
# ============================================================

if CORS_ORIGINS.strip() == "*":

    origins = ["*"]

else:

    origins = [
        origin.strip()
        for origin in CORS_ORIGINS.split(",")
        if origin.strip()
    ]


app.add_middleware(
    CORSMiddleware,

    allow_origins=origins,

    allow_credentials=False,

    allow_methods=[
        "GET",
        "POST",
        "OPTIONS"
    ],

    allow_headers=["*"],
)


# ============================================================
# AWS CLIENTS
# ============================================================

print("========================================")
print("Initializing AWS clients")
print("========================================")
print(f"AWS Region       : {AWS_REGION}")
print(f"Bedrock Model    : {BEDROCK_MODEL_ID}")
print(f"Use S3           : {USE_S3}")
print(f"S3 Bucket        : {S3_BUCKET}")
print(f"CORS Origins     : {origins}")
print("========================================")


# Nova can sometimes take longer than the normal boto3
# defaults. Lambda itself is still controlled by Terraform.
bedrock_config = Config(
    connect_timeout=10,
    read_timeout=300,
    retries={
        "max_attempts": 3,
        "mode": "standard"
    }
)


bedrock_client = boto3.client(
    "bedrock-runtime",
    region_name=AWS_REGION,
    config=bedrock_config
)


if USE_S3:

    s3_client = boto3.client(
        "s3",
        region_name=AWS_REGION
    )

else:

    s3_client = None


# ============================================================
# REQUEST / RESPONSE MODELS
# ============================================================

class ChatRequest(BaseModel):

    message: str = Field(
        ...,
        min_length=1,
        max_length=10000
    )

    session_id: Optional[str] = None


class ChatResponse(BaseModel):

    response: str

    session_id: str


class Message(BaseModel):

    role: str

    content: str

    timestamp: str


# ============================================================
# SESSION VALIDATION
# ============================================================

def validate_session_id(
    session_id: str
) -> str:

    if not session_id:
        raise HTTPException(
            status_code=400,
            detail="Session ID cannot be empty."
        )

    # UUIDs are generated by this application.
    # Only allow safe UUID-like values.
    if not re.fullmatch(
        r"[a-fA-F0-9-]{20,100}",
        session_id
    ):
        raise HTTPException(
            status_code=400,
            detail="Invalid session ID."
        )

    return session_id


# ============================================================
# MEMORY
# ============================================================

def get_memory_path(
    session_id: str
) -> str:

    validate_session_id(session_id)

    return f"{session_id}.json"


def load_conversation(
    session_id: str
) -> List[Dict[str, Any]]:
    """
    Load conversation history from S3 or local storage.
    """

    session_id = validate_session_id(
        session_id
    )

    # ========================================================
    # S3
    # ========================================================

    if USE_S3:

        if not S3_BUCKET:

            raise RuntimeError(
                "USE_S3=true but S3_BUCKET is not configured."
            )

        try:

            response = s3_client.get_object(
                Bucket=S3_BUCKET,
                Key=get_memory_path(session_id)
            )

            body = response["Body"].read().decode(
                "utf-8"
            )

            data = json.loads(body)

            if not isinstance(data, list):
                return []

            return data

        except ClientError as e:

            error_code = (
                e.response
                .get("Error", {})
                .get("Code", "")
            )

            if error_code in [
                "NoSuchKey",
                "404"
            ]:

                return []

            if error_code == "NoSuchBucket":

                raise RuntimeError(
                    f"S3 bucket does not exist: {S3_BUCKET}"
                )

            print(
                f"S3 load error: {error_code}: {e}"
            )

            raise

    # ========================================================
    # LOCAL
    # ========================================================

    os.makedirs(
        MEMORY_DIR,
        exist_ok=True
    )

    file_path = os.path.join(
        MEMORY_DIR,
        get_memory_path(session_id)
    )

    if not os.path.exists(file_path):
        return []

    try:

        with open(
            file_path,
            "r",
            encoding="utf-8"
        ) as f:

            data = json.load(f)

            if not isinstance(data, list):
                return []

            return data

    except json.JSONDecodeError:

        print(
            f"Invalid conversation file: {file_path}"
        )

        return []


def save_conversation(
    session_id: str,
    messages: List[Dict[str, Any]]
):
    """
    Save conversation history to S3 or local storage.
    """

    session_id = validate_session_id(
        session_id
    )

    # ========================================================
    # S3
    # ========================================================

    if USE_S3:

        if not S3_BUCKET:

            raise RuntimeError(
                "USE_S3=true but S3_BUCKET is not configured."
            )

        s3_client.put_object(

            Bucket=S3_BUCKET,

            Key=get_memory_path(session_id),

            Body=json.dumps(
                messages,
                indent=2,
                ensure_ascii=False
            ).encode("utf-8"),

            ContentType="application/json"
        )

        return

    # ========================================================
    # LOCAL
    # ========================================================

    os.makedirs(
        MEMORY_DIR,
        exist_ok=True
    )

    file_path = os.path.join(
        MEMORY_DIR,
        get_memory_path(session_id)
    )

    with open(
        file_path,
        "w",
        encoding="utf-8"
    ) as f:

        json.dump(
            messages,
            f,
            indent=2,
            ensure_ascii=False
        )


# ============================================================
# BEDROCK
# ============================================================

def call_bedrock(
    conversation: List[Dict[str, Any]],
    user_message: str
) -> str:

    if not user_message or not user_message.strip():

        raise HTTPException(
            status_code=400,
            detail="Message cannot be empty."
        )

    # ========================================================
    # SYSTEM PROMPT
    # ========================================================

    try:

        from context import prompt

        system_prompt = prompt()

    except Exception as e:

        print(
            f"Could not load context.prompt(): {e}"
        )

        system_prompt = (
            "You are an AI digital twin assistant. "
            "Answer clearly, accurately, and helpfully."
        )

    # ========================================================
    # BEDROCK HISTORY
    # ========================================================

    messages = []

    # Keep the most recent 50 messages.
    for msg in conversation[-50:]:

        role = msg.get("role")

        content = msg.get("content")

        if role not in [
            "user",
            "assistant"
        ]:
            continue

        if not content:
            continue

        messages.append(
            {
                "role": role,

                "content": [
                    {
                        "text": str(content)
                    }
                ]
            }
        )

    # ========================================================
    # CURRENT USER MESSAGE
    # ========================================================

    messages.append(
        {
            "role": "user",

            "content": [
                {
                    "text": user_message.strip()
                }
            ]
        }
    )

    # ========================================================
    # DEBUG
    # ========================================================

    print("")
    print("========================================")
    print("BEDROCK REQUEST")
    print("========================================")
    print(f"Model ID      : {BEDROCK_MODEL_ID}")
    print(f"AWS Region    : {AWS_REGION}")
    print(f"Messages      : {len(messages)}")
    print("API           : Converse")
    print("========================================")
    print("")

    try:

        # ====================================================
        # CONVERSE
        # ====================================================

        response = bedrock_client.converse(

            modelId=BEDROCK_MODEL_ID,

            system=[
                {
                    "text": system_prompt
                }
            ],

            messages=messages,

            inferenceConfig={
                "maxTokens": 2000,
                "temperature": 0.7,
                "topP": 0.9
            }
        )

        # ====================================================
        # EXTRACT RESPONSE
        # ====================================================

        output = response.get(
            "output",
            {}
        )

        assistant_message = output.get(
            "message",
            {}
        )

        content = assistant_message.get(
            "content",
            []
        )

        text_parts = []

        for item in content:

            if "text" in item:

                text_parts.append(
                    item["text"]
                )

        assistant_response = "".join(
            text_parts
        ).strip()

        if not assistant_response:

            raise RuntimeError(
                "Bedrock returned an empty text response."
            )

        print(
            "Bedrock response received successfully."
        )

        return assistant_response

    except ClientError as e:

        error = e.response.get(
            "Error",
            {}
        )

        error_code = error.get(
            "Code",
            "Unknown"
        )

        error_message = error.get(
            "Message",
            str(e)
        )

        request_id = (
            e.response
            .get("ResponseMetadata", {})
            .get("RequestId")
        )

        print("")
        print("========================================")
        print("BEDROCK ERROR")
        print("========================================")
        print(f"Error Code    : {error_code}")
        print(f"Error Message : {error_message}")
        print(f"Request ID    : {request_id}")
        print(f"Model ID      : {BEDROCK_MODEL_ID}")
        print(f"AWS Region    : {AWS_REGION}")
        print("========================================")
        print("")

        if error_code == "ValidationException":

            raise HTTPException(
                status_code=400,
                detail=(
                    "Bedrock ValidationException: "
                    f"{error_message}"
                )
            )

        if error_code == "AccessDeniedException":

            raise HTTPException(
                status_code=403,
                detail=(
                    "Bedrock AccessDeniedException: "
                    f"{error_message}"
                )
            )

        if error_code == "ResourceNotFoundException":

            raise HTTPException(
                status_code=404,
                detail=(
                    "Bedrock ResourceNotFoundException: "
                    f"{error_message}"
                )
            )

        if error_code == "ThrottlingException":

            raise HTTPException(
                status_code=429,
                detail=(
                    "Bedrock ThrottlingException: "
                    f"{error_message}"
                )
            )

        raise HTTPException(
            status_code=500,
            detail=(
                f"Bedrock error ({error_code}): "
                f"{error_message}"
            )
        )

    except HTTPException:

        raise

    except Exception as e:

        print("")
        print("========================================")
        print("UNEXPECTED BEDROCK ERROR")
        print("========================================")
        print(str(e))
        print("========================================")
        print("")

        raise HTTPException(
            status_code=500,
            detail=f"Bedrock request failed: {str(e)}"
        )


# ============================================================
# ROOT
# ============================================================

@app.get("/")
async def root():

    return {
        "message": "AI Digital Twin API",
        "status": "running",
        "memory_enabled": USE_S3,
        "storage": (
            "S3"
            if USE_S3
            else "local"
        ),
        "aws_region": AWS_REGION,
        "ai_model": BEDROCK_MODEL_ID
    }


# ============================================================
# HEALTH
# ============================================================

@app.get("/health")
async def health_check():

    return {
        "status": "healthy",
        "use_s3": USE_S3,
        "storage": (
            "S3"
            if USE_S3
            else "local"
        ),
        "aws_region": AWS_REGION,
        "bedrock_model": BEDROCK_MODEL_ID
    }


# ============================================================
# CHAT
# ============================================================

@app.post(
    "/chat",
    response_model=ChatResponse
)
async def chat(
    request: ChatRequest
):

    # ========================================================
    # VALIDATE
    # ========================================================

    message = request.message.strip()

    if not message:

        raise HTTPException(
            status_code=400,
            detail="Message cannot be empty."
        )

    # ========================================================
    # SESSION
    # ========================================================

    if request.session_id:

        session_id = validate_session_id(
            request.session_id
        )

    else:

        session_id = str(
            uuid.uuid4()
        )

    print("")
    print("========================================")
    print("CHAT REQUEST")
    print("========================================")
    print(f"Session ID : {session_id}")
    print(f"Message    : {message}")
    print("========================================")
    print("")

    # ========================================================
    # LOAD MEMORY
    # ========================================================

    conversation = load_conversation(
        session_id
    )

    # ========================================================
    # CALL BEDROCK
    # ========================================================

    assistant_response = call_bedrock(
        conversation,
        message
    )

    # ========================================================
    # SAVE MEMORY
    # ========================================================

    timestamp = datetime.now(
        timezone.utc
    ).isoformat()

    conversation.append(
        {
            "role": "user",
            "content": message,
            "timestamp": timestamp
        }
    )

    conversation.append(
        {
            "role": "assistant",
            "content": assistant_response,
            "timestamp": datetime.now(
                timezone.utc
            ).isoformat()
        }
    )

    save_conversation(
        session_id,
        conversation
    )

    # ========================================================
    # RESPONSE
    # ========================================================

    return ChatResponse(
        response=assistant_response,
        session_id=session_id
    )


# ============================================================
# CONVERSATION
# ============================================================

@app.get(
    "/conversation/{session_id}"
)
async def get_conversation(
    session_id: str
):

    try:

        session_id = validate_session_id(
            session_id
        )

        conversation = load_conversation(
            session_id
        )

        return {
            "session_id": session_id,
            "messages": conversation
        }

    except HTTPException:

        raise

    except Exception as e:

        print(
            f"Conversation error: {str(e)}"
        )

        raise HTTPException(
            status_code=500,
            detail=str(e)
        )


# ============================================================
# LOCAL DEVELOPMENT
# ============================================================

if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )
